import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <main className="font-mono font-bold text-xl min-w-full min-h-[100vh] flex items-start p-10 justify-center bg-gray-700 text-white">

        {children}
        </main>
        </body>
    </html>
  );
}
